- name: "Uninstall docker tools and environment"
  hosts: 'all'
  gather_facts: true
  remote_user: startx
  become_method: sudo
  become: yes
  vars:
    docker_edition: 'ce'
    docker_package_state: absent
    docker_install_compose: false
  tasks:
  - name: Ensure docker service is stopped
    systemd:
      name: docker
      state: stopped
  - name: Uninstall docker with geerlingguy.docker role
    include_role: 
      name: geerlingguy.docker
  - name: Ensure Galaxy role for docker runtime are uninstalled
    command: ansible-galaxy uninstall {{ item }}
    with_items:
      - geerlingguy.pip
      - geerlingguy.docker
  - name: Ensure docker runtime packages are uninstalled
    package:
      name: 
      - docker-{{ docker_edition }}
      - docker-{{ docker_edition }}-cli
      state: absent